### ISSUE TITLE
Batching rule not implemented for aten::rsub.Scalar, aten::diag, aten::where.Scalar, aten::allclose.

### ISSUE THREAD

**Issue by JonathanSchmidt1** [zou3519/functorch#26]
Hello and thank you for the great project:
We are using it in a fully differentiable physics code atm and found some use cases that were not covered yet.
We are vmapping some functions that use torch.where and/or torch.diag e.g.:
```python
def set_diagonal_to_inf(hamiltonian, value=10e9):
    """Args:
        hamiltonian: Matrix of hamiltonian (N_k, particle number*N_orbitals, particle number*N_orbitals)
        value: int/ float value the zeros are set to
    Returns:
        Hamiltonian with high eigenvalues for non existing particles/orbitals
    """
    diag = torch.sum(torch.abs(hamiltonian), axis=0)
    diag = torch.where(diag == 0, value, 0.)
    return torch.diag(diag)
```
and got the warning that they were not implemented yet:
functorch/_src/vmap.py:268: UserWarning: Batching rule not implemented for aten::diag falling back to slow (for loop and stack) implementation (Triggered internally at  /tmp/pip-req-build-_exf5lof/functorch/csrc/BatchedFallback.cpp:89.)
  batched_outputs = func(*batched_inputs)
UserWarning: Batching rule not implemented for aten::where.Scalar falling back to slow (for loop and stack) implementation (Triggered internally at  /tmp/pip-req-build-_exf5lof/functorch/csrc/BatchedFallback.cpp:89.)

Another function was constructing a 2d array from an input vector, where each array element was constructed with a different formula. That function was performance relevant but we were able to vectorize it without vmap, anyway it lead to the following warning.
torch/_tensor.py:544: UserWarning: Batching rule not implemented for aten::rsub.Scalar falling back to slow (for loop and stack) implementation (Triggered internally at  /tmp/pip-req-build-_exf5lof/functorch/csrc/BatchedFallback.cpp:89.)
  return _C._VariableFunctions.rsub(self, other)

At last we would like to solve a lot of eigenvalue problems with the symeig solver from xitorch https://github.com/xitorch/xitorch
```python
def eig(ham):
     ham =(ham+ham.T)/2
     ham = xitorch.LinearOperator.m(ham)
     return  xilinalg.symeig(ham)[0]

parallel_solve = vmap(eig,0)
test = torch.rand(7,10,10)
parallel_solve(test)
```
which lead to the following error 
File "xitorch/_core/linop.py", line 100, in m
    is_hermitian = torch.allclose(mat, mat.transpose(-2, -1))
RuntimeError: Batching rule not implemented for aten::allclose. We could not generate a fallback.

Would be great if you can find the time to add some of these, especially the last one.
Ps: thank you for using the same vmap syntax as jax that saved a lot of time converting the code.

**Comment by Chillee** [comment]
Thanks for providing lists of batching rules where we still need to fill in the gaps :) We'll work towards adding them.

Other than allclose (where we couldn't generate a fallback), does the API suffice for your needs? We're looking for feedback on APIs and such :)

> Ps: thank you for using the same vmap syntax as jax that saved a lot of time converting the code.

Yeah, all credit to the Jax team for coming up with such a great API :)

**Comment by Chillee** [comment]
Looking closer at the usage of `aten::allclose`, I'm not sure that you'll be able to vmap through it without some modifications to the library.

Unfortunately, the code looks something like this:
```
is_hermitian: bool = torch.allclose(a, a.t())
```

The problem is that `a` is now batched, so what should `torch.allclose` return? A list of booleans? Then what happens if you have

```
is_hermitian: bool = torch.allclose(a, a.t())
if is_hermitian:
    do foo
else:
   do blah
```

My suspicion is that the code will need to be restructured in order to vmap over it.

**Comment by JonathanSchmidt1** [comment]
Thank you for taking a look at the xitorch issue, than I will rewrite the code  as this check is not 100% required.
Concerning the api if you just use the jax api I have no suggestions for improvements, it already works great.

**Comment by Chillee** [comment]
I suspect that in order to resolve this, we may need to have control flow operators (like Jax's `lax.cond`).
