### ISSUE TITLE
Transforms don't work with new_ones

### ISSUE THREAD

**Issue by Chillee** [zou3519/functorch#29]
```
import torch
from functorch import vmap,

def f(x):
    return x.new_ones(x.shape)

print(vmap(f)(torch.randn(3)))

>>> RuntimeError: DispatchKey FuncTorchBatched doesn't correspond to a device
```

**Comment by zou3519** [comment]
Haven't seen that error message before. For now the fix is the "new_blah hacks": https://github.com/zou3519/functorch/blob/main/functorch/csrc/new_blah_hacks.cpp

**Comment by zou3519** [comment]
I take that back. `new_ones` [isn't an operator](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml), it looks like, so the "new_blah hacks" don't apply to it :/

**Comment by Chillee** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/58405
